2023-04-01 20:03:16 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023413E567C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/5288891/envelope/
2023-04-01 20:03:16 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023413E56808>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/5288891/envelope/
2023-04-01 20:03:16 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023413E8B788>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/5288891/envelope/
